### ISSUE TITLE
Exception: Failed to compile BPF module <text>

### ISSUE THREAD

**Issue by arjuntemura** [UWNetworksLab/meshinsight#12]
I am facing the following error after running the code for Meshinsight's profiler: 

```
ryzen02@ryzen02-rs-iiitd:~/meshinsight$ sudo python3 ./meshinsight/profiler/offline_profiler.py --latency --cpu
18-Jun-23 18:35:42 |     INFO | Starting latency profiling!
In file included from /virtual/main.c:2:
In file included from include/uapi/linux/ptrace.h:143:
In file included from ./arch/x86/include/asm/ptrace.h:5:
./arch/x86/include/asm/segment.h:266:2: error: expected '(' after 'asm'
        alternative_io ("lsl %[seg],%[p]",
        ^
./arch/x86/include/asm/alternative.h:240:2: note: expanded from macro 'alternative_io'
        asm_inline volatile (ALTERNATIVE(oldinstr, newinstr, feature)   \
        ^
include/linux/compiler_types.h:214:24: note: expanded from macro 'asm_inline'
#define asm_inline asm __inline
                       ^
/virtual/main.c:53:9: error: no member named 'atomic_increment' in 'struct avg_table_t'
    avg.atomic_increment(lat, delta);
    ~~~ ^
/virtual/main.c:54:9: error: no member named 'atomic_increment' in 'struct avg_table_t'
    avg.atomic_increment(cnt);
    ~~~ ^
/virtual/main.c:59:10: error: no member named 'atomic_increment' in 'struct dist_table_t'
    dist.atomic_increment(bpf_log2l(delta));
    ~~~~ ^
4 errors generated.
Traceback (most recent call last):
  File "/home/ryzen02/meshinsight/meshinsight/profiler/latency/funclatency.py", line 345, in <module>
    b = BPF(text=bpf_text)
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 343, in __init__
    raise Exception("Failed to compile BPF module %s" % (src_file or "<text>"))
Exception: Failed to compile BPF module <text>
Traceback (most recent call last):
  File "./meshinsight/profiler/offline_profiler.py", line 596, in <module>
    syscall_overhead  = profile_syscall(args.duration)
  File "./meshinsight/profiler/offline_profiler.py", line 41, in profile_syscall
    result = subprocess.run(cmd, stdout=subprocess.PIPE, check=True)
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['python3', '/home/ryzen02/meshinsight/meshinsight/profiler/latency/funclatency.py', '-p 6234', 'c:getpid', '-d 30']' returned non-zero exit status 1.
```

**I am using Linux kernel version 5.4.0 , Ubuntu 18.04, Python 3.8, libllvm 6.0 , libclang 6.0 , llvm 6.0**

**I would be obliged if someone can help with this !**

**Comment by Romero027** [comment]
Thanks for trying MeshInsight!

It seems to be a BCC issue - will this help? https://github.com/iovisor/bcc/issues/3752

**Comment by Romero027** [comment]
MeshInsight should work on Ubuntu 20.04 and 22.04 (I think).

**Comment by arjuntemura** [comment]
> MeshInsight should work on Ubuntu 20.04.

Hi @Romero027 
The LLVM version I was using (llvm 6.0) was not compatible with bcc. https://github.com/iovisor/bcc/issues/3808
I therefore installed bcc v0.24.0 and it worked perfectly on Ubuntu 18.04 and kernel version 4.15. 
However after I ran the profiler I got this error: 
```

 22-Jun-23 17:10:27 |     INFO | Starting latency profiling!
Traceback (most recent call last):
  File "./meshinsight/profiler/offline_profiler.py", line 601, in <module>
    latency_profile = run_latency_experiment(p, request_sizes, args, syscall_overhead)
  File "./meshinsight/profiler/offline_profiler.py", line 212, in run_latency_experiment
    envoy_pid = get_pid("envoy")
  File "./meshinsight/profiler/offline_profiler.py", line 75, in get_pid
    pid = [i for i in result if "--concurrency" in i][0].split()[1]
IndexError: list index out of range
```
